### ISSUE TITLE
Change title

### ISSUE THREAD

**Issue by Klypalskyi** [rumess/react-flip-countdown#1]
Hello, how I can change titles to "Days", "Houres" and "Minutes". Is it possible? Or can you provide options for doing that?

**Comment by caa1982** [comment]
change the color too!

**Comment by rumeshudash** [comment]
> Hello, how I can change titles to "Days", "Houres" and "Minutes". Is it possible? Or can you provide options for doing that?

@Klypalskyi 
https://github.com/rumess/react-flip-countdown#change-title
