### ISSUE TITLE
add index.d.ts 

### ISSUE THREAD

**Issue by Hexi1997** [rumess/react-flip-countdown#12]
interface ICountDown {
  hideYear?: boolean
  hideMonth?: boolean
  hideDay?: boolean
  hideHour?: boolean
  hideSecond?: boolean
  yearTitle?: string
  monthTitle?: string
  dayTitle?: string
  hourTitle?: string
  minuteTitle?: string
  secondTitle?: string
  endAtZero?: boolean
  theme?: 'dark' | 'light'
  titlePosition?: 'top' | 'bottom'
  size?: 'large' | 'medium' | 'small' | 'extra-small'
  endAt: string
}

declare module '@rumess/react-flip-countdown' {
  export default function FlipCountdown(props: ICountDown): JSX.Element
}

**Comment by Hexi1997** [comment]
建议修改readme中的格式，改成endAt="2021/11/9 07:00:00 UTC" 兼容iphone

**Comment by rumeshudash** [comment]
> interface ICountDown { hideYear?: boolean hideMonth?: boolean hideDay?: boolean hideHour?: boolean hideSecond?: boolean yearTitle?: string monthTitle?: string dayTitle?: string hourTitle?: string minuteTitle?: string secondTitle?: string endAtZero?: boolean theme?: 'dark' | 'light' titlePosition?: 'top' | 'bottom' size?: 'large' | 'medium' | 'small' | 'extra-small' endAt: string }
> 
> declare module '@rumess/react-flip-countdown' { export default function FlipCountdown(props: ICountDown): JSX.Element }

We are planning to migrate this project to Typescript.

**Comment by rumeshudash** [comment]
> 建议修改readme中的格式，改成endAt="2021/11/9 07:00:00 UTC" 兼容iphone

This project is using momentjs. So the props 'endAt' will accept any format momentjs accepts. It was only for example purposes.
In the future, we are planning to migrate this project to date-fns.

Thank you for your feedbacks.
