### ISSUE TITLE
Titles Moving around with Every Second

### ISSUE THREAD

**Issue by benwinding** [rumess/react-flip-countdown#13]
![Kapture 2021-12-06 at 10 52 13](https://user-images.githubusercontent.com/11782590/144769226-88b3fd10-ea93-4712-a9ee-953920b9e2f4.gif)

Just looks a bit clunky, so can't use this for a production product 😟 

Might be the font not being monospace perhaps?

**Comment by benwinding** [comment]
Much less Janky with a monospace font 👌 
![Kapture 2021-12-06 at 11 01 16](https://user-images.githubusercontent.com/11782590/144769507-58c720ef-c898-4668-8095-6581e4903517.gif)

**Comment by rumeshudash** [comment]
Fixed in #17
