### ISSUE TITLE
How to styling the clock ?

### ISSUE THREAD

**Issue by VietnameseRick** [rumess/react-flip-countdown#16]
Are there any way to styling the clock ? Like changing the colour of background or the font of the clock ?

**Comment by rumeshudash** [comment]
@VietnameseRick You can use the below CSS variables to customize background and text colors. As of v1.2.6. #18 

`--background-color: #222;`
`--background-bottom-color: #393939;`
`--text-color: #ccc;`
`--text-bottom-color: #fff;`
