### ISSUE TITLE
how can i custom size?

### ISSUE THREAD

**Issue by devzucca** [rumess/react-flip-countdown#20]
hi, thanks fot this, how can i custom size?

**Comment by rumeshudash** [comment]
@devzucca 
You can follow this doc link for size props.
https://github.com/rumess/react-flip-countdown#size

**Comment by devzucca** [comment]
> @devzucca You can follow this doc link for size props. https://github.com/rumess/react-flip-countdown#size

Yes, I saw the documentation, but I would like to change it to specific sizes such as pixels, can I pass a number or px type?

**Comment by rumeshudash** [comment]
> > @devzucca You can follow this doc link for size props. https://github.com/rumess/react-flip-countdown#size
> 
> Yes, I saw the documentation, but I would like to change it to specific sizes such as pixels, can I pass a number or px type?

Sorry, not possible right now.
