### ISSUE TITLE
Timer at zero

### ISSUE THREAD

**Issue by abhinavsri360** [rumess/react-flip-countdown#5]
Timestamp is displayed when timer reaches zero

**Comment by rumeshudash** [comment]
@abhinavsri360
You can pass children to the Component, which will be displayed after timer is ended.

**_Example:_** 
`
<FlipCountdown endAt= {new Date( Date.now() + 1000 * 60 * 60 * 13 ).toUTCString() }>
// Your message or component here.
</FlipCountdown>
`

**Comment by abhinavsri360** [comment]
I wanted to show 00:00:00:00 when the timer ends, not a message. In the same styling format.

**Comment by rumeshudash** [comment]
@abhinavsri360 
This might solve your issue.
https://github.com/rumess/react-flip-countdown#end-as-zero

**Comment by abhinavsri360** [comment]
@rumeshudash 
Great, thanks for the update!
