### ISSUE TITLE
Trigger function on timeout

### ISSUE THREAD

**Issue by 1NT18IS066** [rumess/react-flip-countdown#8]
It would be great if it can triggers a function on timeout

**Comment by 1NT18IS066** [comment]
its ok u have given the source i can modify myself. btw thnx for the source

**Comment by 1NT18IS066** [comment]
Thanks for the source i modified the source according to my need. And its working like a charm. Anyways consider it as a suggestion.

**Comment by rumeshudash** [comment]
@1NT18IS066 
Thanks for the suggestion. 😃
