### ISSUE TITLE
Duration Timer

### ISSUE THREAD

**Issue by abhinavsri360** [rumess/react-flip-countdown#9]
It would be great if there could be a parameter named `duration`, wherein anyone would pass the duration for which the timer is supposed to run.

**Comment by rumeshudash** [comment]
> It would be great if there could be a parameter named `duration`, wherein anyone would pass the duration for which the timer is supposed to run.

Duration as in milliseconds?

**Comment by abhinavsri360** [comment]
Yes

**Comment by rumeshudash** [comment]
Cool. But it will be issue when user reload the page and every time duration will be the same. Unless duration is in unix timestamp.

**Comment by abhinavsri360** [comment]
Ya right, in that case I think it's best to configure UNIX timestamp.
